import {
  Contact,
  Meeting,
  FollowUp,
  Note,
  Reminder,
  ActivityHistory,
  UserSettings,
} from "@/types";
import { format, subDays, addDays, subMinutes, addHours } from "date-fns";
import { getAvatarColor } from "@/lib/utils";
import { DEFAULT_USER_SETTINGS } from "@/lib/constants";
import { calculateReminderTime } from "@/lib/date-utils";

export function generateSeedData() {
  const today = format(new Date(), "yyyy-MM-dd");
  const yesterday = format(subDays(new Date(), 1), "yyyy-MM-dd");
  const twoDaysAgo = format(subDays(new Date(), 2), "yyyy-MM-dd");
  const tomorrow = format(addDays(new Date(), 1), "yyyy-MM-dd");
  const nextWeek = format(addDays(new Date(), 5), "yyyy-MM-dd");

  const nowIso = new Date().toISOString();
  const yesterdayIso = subDays(new Date(), 1).toISOString();
  const twoDaysAgoIso = subDays(new Date(), 2).toISOString();

  const contacts: Contact[] = [
    {
      id: "cnt_1",
      name: "Rajesh Kumar",
      company: "ABC Industries",
      mobile: "+91 98201 45678",
      email: "rajesh.kumar@abcindustries.com",
      address: "Bandra Kurla Complex, Mumbai, MH",
      notes: "Key decision maker for enterprise ERP rollout. Prefers morning calls.",
      avatarColor: getAvatarColor("Rajesh Kumar"),
      lastContactedAt: yesterdayIso,
      createdAt: twoDaysAgoIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "cnt_2",
      name: "Priya Sharma",
      company: "XYZ Solutions",
      mobile: "+91 98112 34567",
      email: "priya.s@xyzsolutions.in",
      address: "Indiranagar, Bengaluru, KA",
      notes: "VP of Product. Interested in our Q3 custom integration proposal.",
      avatarColor: getAvatarColor("Priya Sharma"),
      lastContactedAt: twoDaysAgoIso,
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "cnt_3",
      name: "Suresh Rao",
      company: "Tech Corp International",
      mobile: "+91 98450 98765",
      email: "suresh.rao@techcorpglobal.com",
      address: "HITEC City, Hyderabad, TS",
      notes: "CTO. Reviewing annual SLA contracts and cloud migration budget.",
      avatarColor: getAvatarColor("Suresh Rao"),
      lastContactedAt: twoDaysAgoIso,
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "cnt_4",
      name: "Anil Kumar",
      company: "ABC Industries",
      mobile: "+91 98334 11223",
      email: "anil.k@abcindustries.com",
      address: "Bandra Kurla Complex, Mumbai, MH",
      notes: "Head of Procurement. Handles vendor onboarding and invoice processing.",
      avatarColor: getAvatarColor("Anil Kumar"),
      lastContactedAt: yesterdayIso,
      createdAt: twoDaysAgoIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "cnt_5",
      name: "Deepika Patel",
      company: "Nexus Global Logistics",
      mobile: "+91 99099 87654",
      email: "deepika.patel@nexusglobal.com",
      address: "Navrangpura, Ahmedabad, GJ",
      notes: "COO. Looking for warehouse dispatch tracking alerts.",
      avatarColor: getAvatarColor("Deepika Patel"),
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "cnt_6",
      name: "Amit Verma",
      company: "Pinnacle Media Networks",
      mobile: "+91 98100 54321",
      email: "amit.verma@pinnaclemedia.in",
      address: "Connaught Place, New Delhi, DL",
      notes: "Marketing Director. Finalizing brand launch sponsorships.",
      avatarColor: getAvatarColor("Amit Verma"),
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "cnt_7",
      name: "Sunita Reddy",
      company: "Vertex Healthcare Capital",
      mobile: "+91 97000 67890",
      email: "sunita.reddy@vertexcap.com",
      address: "Banjara Hills, Hyderabad, TS",
      notes: "Managing Partner. Schedule quarterly portfolio review.",
      avatarColor: getAvatarColor("Sunita Reddy"),
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "cnt_8",
      name: "Vikram Malhotra",
      company: "Summit Retail Ventures",
      mobile: "+91 99200 12345",
      email: "v.malhotra@summitretail.com",
      address: "Lower Parel, Mumbai, MH",
      notes: "Founder & CEO. High priority enterprise lead.",
      avatarColor: getAvatarColor("Vikram Malhotra"),
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
  ];

  const meetings: Meeting[] = [
    {
      id: "mtg_1",
      contactId: "cnt_1",
      title: "Quarterly Strategy & ERP Scope Discussion",
      date: today,
      time: "09:00",
      location: "ABC Industries HQ, Bandra / Google Meet",
      purpose: "Finalize module roadmap and approve milestones for Q4 release.",
      notes: "Bring updated presentation deck and revised pricing structure.",
      reminder: "1_hour",
      status: "pending",
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "mtg_2",
      contactId: "cnt_3",
      title: "Technical Architecture Review",
      date: today,
      time: "14:00",
      location: "Zoom Video Conference",
      purpose: "Deep-dive with Suresh and lead security architect.",
      notes: "Send security compliance whitepaper 30 mins before call.",
      reminder: "1_hour",
      status: "pending",
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "mtg_3",
      contactId: "cnt_5",
      title: "Dispatch Automation Demo",
      date: tomorrow,
      time: "11:00",
      location: "Microsoft Teams",
      purpose: "Demonstrate live webhook alerts & shipment tracking.",
      reminder: "1_hour",
      status: "pending",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "mtg_4",
      contactId: "cnt_8",
      title: "Initial Partnership Exploratory Call",
      date: yesterday,
      time: "16:00",
      location: "Phone Call",
      purpose: "Discuss multi-store retail sync requirements.",
      notes: "Need to follow up regarding custom quote.",
      reminder: "30_min",
      status: "completed",
      completedAt: yesterdayIso,
      createdAt: twoDaysAgoIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "mtg_5",
      contactId: "cnt_6",
      title: "Media Campaign Sync & Budget Signoff",
      date: yesterday,
      time: "10:30",
      location: "New Delhi Office",
      purpose: "Review quarterly sponsor deliverables.",
      notes: "Rescheduled by client due to offsite leadership meeting.",
      reminder: "1_hour",
      status: "rescheduled",
      createdAt: twoDaysAgoIso,
      updatedAt: yesterdayIso,
    },
  ];

  const followUps: FollowUp[] = [
    {
      id: "flw_1",
      contactId: "cnt_2",
      title: "Send revised proposal with tiered SaaS discounts",
      date: today,
      time: "11:30",
      notes: "Priya requested a 15% discount breakdown for 100+ seats.",
      reminder: "1_hour",
      status: "pending",
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "flw_2",
      contactId: "cnt_4",
      title: "Confirm GST billing details and purchase order approval",
      date: today,
      time: "16:30",
      notes: "Ensure vendor onboarding packet is signed by finance team.",
      reminder: "1_hour",
      status: "pending",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "flw_3",
      contactId: "cnt_7",
      title: "Follow up on term sheet feedback",
      date: yesterday,
      time: "15:00",
      notes: "Sunita requested 48 hours to review with the investment committee.",
      reminder: "1_hour",
      status: "pending", // Will be evaluated as overdue by StatusEngine!
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "flw_4",
      contactId: "cnt_1",
      title: "Follow up on IT security questionnaire signoff",
      date: twoDaysAgo,
      time: "11:00",
      notes: "Overdue follow-up requiring immediate call to Rajesh.",
      reminder: "1_hour",
      status: "pending", // Will be evaluated as overdue!
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "flw_5",
      contactId: "cnt_8",
      title: "Send customized retail enterprise quotation",
      date: tomorrow,
      time: "10:00",
      notes: "Prepare standard 3-year enterprise agreement draft.",
      reminder: "1_hour",
      status: "pending",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "flw_6",
      contactId: "cnt_3",
      title: "Confirm cloud benchmark testing sandbox credentials",
      date: nextWeek,
      time: "14:30",
      notes: "Setup temporary staging keys for tech evaluation team.",
      reminder: "1_hour",
      status: "pending",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
  ];

  const notes: Note[] = [
    {
      id: "not_1",
      contactId: "cnt_1",
      meetingId: "mtg_1",
      activityType: "meeting",
      note: "Rajesh confirmed their board approved budget for the new system. Expecting contract signing by end of month.",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "not_2",
      contactId: "cnt_2",
      followUpId: "flw_1",
      activityType: "call",
      note: "Spoke with Priya on phone. Requested volume tier pricing for 50, 100, and 250 user bands.",
      createdAt: twoDaysAgoIso,
      updatedAt: twoDaysAgoIso,
    },
    {
      id: "not_3",
      contactId: "cnt_8",
      meetingId: "mtg_4",
      activityType: "meeting",
      note: "Great exploratory discussion with Vikram. They want to rollout across 45 flagship stores nationwide in Q4.",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
    {
      id: "not_4",
      contactId: "cnt_4",
      activityType: "call",
      note: "Quick check-in call regarding procurement workflow. Anil confirmed all tax documents are in order.",
      createdAt: yesterdayIso,
      updatedAt: yesterdayIso,
    },
  ];

  const reminders: Reminder[] = [];
  const history: ActivityHistory[] = [
    {
      id: "his_1",
      contactId: "cnt_1",
      activityType: "contact",
      activityId: "cnt_1",
      action: "created",
      createdAt: twoDaysAgoIso,
    },
    {
      id: "his_2",
      contactId: "cnt_1",
      activityType: "meeting",
      activityId: "mtg_1",
      action: "created",
      newData: { title: "Quarterly Strategy & ERP Scope Discussion", date: today, time: "09:00" },
      createdAt: twoDaysAgoIso,
    },
    {
      id: "his_3",
      contactId: "cnt_1",
      activityType: "call",
      activityId: "call_1",
      action: "called",
      createdAt: yesterdayIso,
    },
    {
      id: "his_4",
      contactId: "cnt_1",
      activityType: "note",
      activityId: "not_1",
      action: "note_added",
      newData: { snippet: "Rajesh confirmed their board approved budget..." },
      createdAt: yesterdayIso,
    },
    {
      id: "his_5",
      contactId: "cnt_8",
      activityType: "meeting",
      activityId: "mtg_4",
      action: "completed",
      createdAt: yesterdayIso,
    },
    {
      id: "his_6",
      contactId: "cnt_6",
      activityType: "meeting",
      activityId: "mtg_5",
      action: "rescheduled",
      previousData: { date: twoDaysAgo, time: "10:30" },
      newData: { date: yesterday, time: "10:30" },
      reason: "Client offsite meeting conflict",
      createdAt: yesterdayIso,
    },
  ];

  return {
    contacts,
    meetings,
    followUps,
    notes,
    reminders,
    history,
    settings: DEFAULT_USER_SETTINGS,
  };
}
